## Constants

#### You can create constants of scalar or tensor values.
#### tf . constant ( value , dtype = None , shape = None , name = 'Const' , verify_shape = False)

In [ ]:
import tensorflow as tf

In [ ]:
# constant of 1d tensor (vector)
a = tf.constant([ 2 , 2 ], name = "vector")
# constant of 2x2 tensor (matrix)
b = tf.constant ([[ 0 , 1 ], [ 2 , 3 ]], name = "matrix")

#### You can create tensors whose elements are of a specific value similar to numpy.zeros, numpy.zeros_like, numpy.ones, numpy.ones_like.

In [ ]:
#tf.zeros( shape , dtype = tf.float32 , name = None)
tf.zeros([ 2 , 3 ], tf.int32 )
tf.ones([ 2 , 3 ], tf.int32 )

In [ ]:
with tf.Session() as sess:
    result = sess.run(tf.ones([ 2 , 3 ], tf.int32 ))
    print (result)

#### You can create constants that are sequences

In [ ]:
# tf.linspace( start , stop , num , name = None)
lin = tf.linspace( 10.0 , 13.0 , 4 , name = "linspace" )

with tf.Session() as sess:
    result = sess.run(lin)
    print (result)

In [ ]:
# tf.range( start , limit = None , delta = 1 , dtype = None , name = 'range')

r1 = tf.range(2,20,5)
r2 = tf.range(10)

with tf.Session() as sess:
    result1 = sess.run(r1)
    result2 = sess.run(r2)
    print (result1)
    print (result2)

#### Note that unlike NumPy or Python sequences, TensorFlow sequences are not iterable.

#### for _ in np . linspace ( 0 , 10 , 4 ): # OK                                                                                                                                                             

#### for _ in tf . linspace ( 0 , 10 , 4 ): # TypeError("'Tensor' object is not iterable.")                                                                                          

#### for _ in range ( 4 ): # OK                                                                                                                                                                                     

#### for _ in tf . range ( 4 ): # TypeError("'Tensor' object is not iterable.")

In [ ]:
my_const = tf.constant([1.0,2.0], name="my_const")
with tf.Session() as sess:
    print (sess.graph.as_graph_def())

# Variables

To declare a variable, you create an instance of the class tf.Variable.

In [ ]:
#create variable a with scalar value
a = tf.Variable( 2 , name = "scalar" )
#create variable b as a vector
b = tf.Variable([ 2 , 3 ], name = "vector" )
#create variable c as a 2x2 matrix
c = tf.Variable([[ 0 , 1 ], [ 2 , 3 ]], name = "matrix" )
# create variable W as 784 x 10 tensor, filled with zeros
W = tf.Variable( tf . zeros ([ 784 , 10 ]))


### You have to initialize variables before using them
The easiest way is initializing all variables at once using: tf.global_variables_initializer()

In [ ]:
init = tf.global_variables_initializer ()
with tf.Session () as sess:
    sess.run( init)

In [ ]:
#Initialize only a subset of variables:
init_ab = tf.variables_initializer([a, b], name="init_ab")
with tf.Session() as sess:
    sess.run(init_ab)

In [ ]:
#Initialize a single variable
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)

Evaluate values of variables

If we print the initialized variable, we only see the tensor object.

In [ ]:
# W is a random 700 x 100 variable object
W = tf.Variable(tf.truncated_normal([5, 2]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W)

In [ ]:
#To get the value of a variable, we need to evaluate it using eval()
W = tf.Variable(tf.truncated_normal([5, 2]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W.eval())

Assign values to variables
We can assign a value to a variable using tf.Variable.assign()

In [ ]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print (W.eval ()) # >> 10

In [ ]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session () as sess:
    sess.run(assign_op)
    print (W.eval()) # >> 100

In [ ]:
#You don’t need to initialize variable because assign_op does it for you
#In fact, initializer op is the assign op that assigns the variable’s initial value to the variable itself.

##For simple incrementing and decrementing of variables, TensorFlow includes the
tf.Variable.assign_add() and tf.Variable.assign_sub() methods. Unlike tf.Variable.assign(),
tf.Variable.assign_add() and tf.Variable.assign_sub() don’t initialize your variables for you
because these ops depend on the initial values of the variable.

In [ ]:
W = tf.Variable(10)
with tf.Session() as sess:
    sess.run(W.initializer)
    print (sess.run(W.assign_add(10))) # >> 20
    print (sess.run(W.assign_sub(2))) # >> 18

### Placeholders
##### Place holders are variables with no values, but the can be fed with balues later during execution
we can assemble the graphs first without knowing the values needed for
computation. This is equivalent to defining the function of x, y without knowing the values of x, y.
For example, f(x, y) = x*2 + y.
x, y are placeholders for the actual values.

Defining a Placeholder:
tf.placeholder(dtype,shape=None, name=None)

Dtype-required parameter that specifies of the data type of the value of the placeholder.

Shape specifies the shape of the tensor that can be accepted as actual value for the
placeholder. shape=None means that tensors of any shape will be accepted.
You should always define the shape of your placeholders as detailed as possible.

Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.

#### Feeding value into placeholder through a dictionary

In [1]:
import tensorflow as tf
x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as sess:
    result = sess.run(y)
    print(result)

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-34986d001a07>", line 2, in <module>
    x = tf.placeholder("float", None)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\uid38717\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


In [2]:
with tf.Session() as sess:
    result = sess.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[ 2.  4.  6.]


In [3]:
x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as sess:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = sess.run(y, feed_dict={x: x_data})
    print(result)

[[  2.   4.   6.]
 [  8.  10.  12.]]


In [4]:
c = tf.placeholder(tf.float32)
d = tf.placeholder(tf.float32)

# Add the two placeholders.
z = c + d
with tf.Session() as sess:
# Specify feed_dict with named parameter.
    result = sess.run(z,feed_dict={c: 2.1, d: 1.5})
    print(result)

3.6


In [5]:
# visualizing it on tensorboard
writer = tf.summary.FileWriter('./my_graph',sess.graph)